### ISSUE TITLE
Params

### ISSUE THREAD

**Issue by conradludgate** [conradludgate/openapi-tide#3]
For path items, params can be specified on the Path Item, as well as in the operations.

```yaml:
/example/{item1}:
  params:
    item1:
      type: string
      in: path
  get:
    params:
      item2:
        type: integer
        in: query
```

would produce the corresponding handle path `"/example/:item1"` for tide and the following data structure for parameter decoding

```rust
struct Params {
    item1: String,
    query: ParamsQuery,
}

#[derive(serde::Deserialize)]
struct ParamsQuery {
    item2: isize,
}

impl<T> Decoder<T> for Params {
    async fn decode(req: &mut tide::Request<T>) -> tide::Result<Self> {
        Ok(Self {
            item1: req.param("item1")?,
            query: req.query()?,
        })
    }
}
```

[query](https://docs.rs/tide/0.11.0/tide/struct.Request.html#method.query) decodes the url query into a serde object so for convenience I've got it wrapped into another struct.
Similarly, [param](https://docs.rs/tide/0.11.0/tide/struct.Request.html#method.param) works on any type that impls FromStr
